"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Search, FlaskConical, LoaderCircle } from "lucide-react";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function SimulatorHome() {
  const router = useRouter(); const [q, setQ] = useState(""); const [results, setResults] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const search = async () => { if (!q.trim()) return; setLoading(true); setError(""); try { setResults(await api<any[]>(`/assets/search?q=${encodeURIComponent(q.trim())}`)); } catch (e: any) { setError(e?.message || "Live market search is unavailable."); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-5xl space-y-8"><div className="max-w-3xl"><p className="section-kicker">Decision lab</p><h1 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-6xl">Stress-test an <span className="text-[var(--accent)]">investment idea.</span></h1><p className="mt-4 text-[var(--muted)] sm:text-lg">Search the live market first. Then choose the company and build scenarios from its current provider data.</p></div><Card className="p-5 sm:p-7"><div className="flex items-center gap-3"><Search className="text-[var(--muted)]"/><input value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => e.key === "Enter" && search()} placeholder="Search a company or ticker…" className="w-full bg-transparent text-base outline-none placeholder:text-[var(--muted-2)]"/><Button onClick={search} disabled={loading}>{loading ? <LoaderCircle className="animate-spin" size={16}/> : "Search"}</Button></div>{error && <p className="mt-4 text-sm text-[var(--danger)]">{error}</p>}</Card><div className="grid gap-3 sm:grid-cols-2">{results.map(a => <button key={a.symbol} onClick={() => router.push(`/simulate/${encodeURIComponent(a.symbol)}`)} className="group rounded-3xl border border-[var(--line)] bg-white/[.025] p-5 text-left transition hover:-translate-y-1 hover:border-white/20 hover:bg-white/[.045]"><div className="flex items-start justify-between"><div><p className="text-[11px] uppercase tracking-[.15em] text-[var(--muted)]">{a.symbol} · {a.exchange}</p><h2 className="mt-2 text-lg font-bold">{a.name}</h2></div><FlaskConical size={18} className="text-[var(--accent)]"/></div><div className="mt-7 flex items-center justify-between text-sm"><span className="text-[var(--muted)]">Open decision lab</span><ArrowRight size={16} className="transition group-hover:translate-x-1"/></div></button>)}</div>{!results.length && !loading && <Card className="grid min-h-[360px] place-items-center p-8 text-center"><div><FlaskConical size={36} className="mx-auto text-[var(--muted)]"/><h2 className="mt-5 text-2xl font-bold">No scenario yet.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--muted)]">Search a real company above. THESIS will refuse to fabricate a scenario when the provider does not return enough verified financial data.</p></div></Card>}</div>;
}
