"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowRight, FlaskConical, LoaderCircle, ShieldAlert, Target, TrendingDown, TrendingUp } from "lucide-react";
import { motion } from "motion/react";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Reveal } from "@/components/ui/primitives";

export default function Simulate(){
  const p=useParams<{symbol:string}>(); const symbol=decodeURIComponent(String(p.symbol??""));
  const [amount,setAmount]=useState(10000),[years,setYears]=useState(5),[behavior,setBehavior]=useState("hold"),[result,setResult]=useState<any>(),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const run=async()=>{setLoading(true);setError("");try{setResult(await api<any>('/simulation',{method:'POST',body:JSON.stringify({symbol,amount,years,behaviorResponse:behavior})}))}catch(e:any){setError(e?.message??"Simulation unavailable")}finally{setLoading(false)}};
  useEffect(()=>{if(symbol)run()},[symbol]);
  const money=(v:number,currency="INR")=>`${currency==="USD"?"$":"₹"}${Number(v).toLocaleString("en-IN")}`;
  return <div className="mx-auto max-w-6xl space-y-8"><Reveal><p className="section-kicker">Decision lab · {symbol}</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">Stress-test <span className="text-[var(--accent)]">this company.</span></h1><p className="mt-4 max-w-2xl text-[var(--muted)]">This is not a generic quiz. The scenarios below use {symbol}&apos;s actual growth, profitability, valuation and risk context to show what could change your decision.</p></Reveal>
    {result&&<Card className="border-[var(--accent)]/10 bg-[var(--accent)]/[.025] p-5"><div className="flex flex-wrap items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><Target size={19}/></div><div><p className="text-xs text-[var(--muted)]">You are stress-testing</p><p className="font-bold">{result.asset.name} · {result.asset.symbol}</p></div><div className="ml-auto flex gap-2 text-xs"><span className="pill px-3 py-1.5">Risk {result.asset.risk}</span><span className="pill px-3 py-1.5">Hype {result.asset.hype}</span><span className="pill px-3 py-1.5">Quality {result.asset.quality}</span></div></div></Card>}
    <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Reveal><Card className="p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><FlaskConical size={18}/></div><div><p className="section-kicker">Inputs</p><p className="font-semibold">Change the decision</p></div></div><label className="mt-8 block text-xs uppercase tracking-[.15em] text-[var(--muted)]">Amount you are considering</label><div className="mt-2 flex items-center rounded-2xl border border-[var(--line)] bg-white/[.025] px-4"><span className="text-[var(--muted)]">₹</span><input min={100} type="number" value={amount} onChange={e=>setAmount(Math.max(100,Number(e.target.value)||100))} className="w-full bg-transparent px-2 py-4 text-2xl font-bold outline-none"/></div><label className="mt-7 block text-xs uppercase tracking-[.15em] text-[var(--muted)]">Time horizon</label><div className="mt-2 grid grid-cols-4 gap-2">{[1,3,5,10].map(y=><button key={y} onClick={()=>setYears(y)} className={`rounded-xl border px-3 py-3 text-sm font-semibold transition ${years===y?'border-[var(--accent)]/30 bg-[var(--accent-soft)] text-[var(--accent)]':'border-[var(--line)] text-[var(--muted)] hover:text-white'}`}>{y}y</button>)}</div><label className="mt-7 block text-xs uppercase tracking-[.15em] text-[var(--muted)]">If {symbol} falls sharply after you buy</label><div className="mt-2 space-y-2">{[['sell','Sell immediately'],['hold','Hold and reassess the thesis'],['buy','Add more only if the thesis improves'],['unsure','I don’t know yet']].map(x=><button key={x[0]} onClick={()=>setBehavior(x[0])} className={`flex w-full items-center justify-between rounded-xl border px-4 py-3 text-left text-sm transition ${behavior===x[0]?'border-[var(--accent)]/30 bg-[var(--accent-soft)]':'border-[var(--line)] hover:bg-white/[.04]'}`}>{x[1]}<span className={`h-3 w-3 rounded-full border ${behavior===x[0]?'border-[var(--accent)] bg-[var(--accent)]':'border-white/20'}`}/></button>)}</div><Button className="mt-7 w-full" onClick={run} disabled={loading}>{loading?<><LoaderCircle className="animate-spin" size={16}/>Recalculating…</>:<>Run {symbol} simulation <ArrowRight size={16}/></>}</Button>{error&&<p className="mt-3 text-xs text-[var(--danger)]">{error}</p>}</Card></Reveal>
      <Reveal delay={.06}><Card className="h-full p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">{years}-year scenario range</p><h2 className="mt-2 text-2xl font-bold">Three different futures for {symbol}</h2></div><div className="pill px-3 py-1.5 text-xs text-[var(--muted)]">Educational only</div></div>{result?<div className="mt-8 space-y-3">{[["bull","Bull",TrendingUp,"#78e6b0"],["base","Base",Target,"#d9ff62"],["bear","Bear",TrendingDown,"#ff6b7a"]].map(([key,label,Icon,color],i)=>{const x=result.scenarios[key as string];return <motion.div initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} transition={{delay:i*.08}} key={key as string} className="relative overflow-hidden rounded-2xl border border-[var(--line)] p-5"><div className="flex items-start justify-between gap-5"><div><div className="flex items-center gap-2"><Icon size={15} style={{color:color as string}}/><p className="text-xs uppercase tracking-[.16em] text-[var(--muted)]">{label as string}</p></div><p className="mt-3 text-3xl font-black">{money(x.value,result.asset.currency)}</p><p className="mt-1 text-xs text-[var(--muted)]">{x.annualRate}% modeled annual rate</p></div><div className="max-w-xs text-right text-sm leading-6 text-[var(--muted)]">{x.cause}</div></div></motion.div>})}</div>:<div className="grid min-h-[420px] place-items-center text-center"><div><FlaskConical size={34} className="mx-auto text-[var(--muted)]"/><p className="mt-4 font-semibold">Run the company-specific scenario</p><p className="mt-1 max-w-sm text-sm text-[var(--muted)]">The model will use the asset&apos;s own growth, valuation and risk data.</p></div></div>}{result&&<><div className="mt-5 rounded-2xl border border-[var(--warning)]/15 bg-[var(--warning)]/[.04] p-5"><div className="flex gap-3"><ShieldAlert size={18} className="mt-0.5 text-[var(--warning)]"/><div><p className="font-semibold">Behavioral stress test</p><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{result.stress.question}</p><p className="mt-3 text-sm leading-6 text-white">{result.stress.insight}</p></div></div></div><div className="mt-5 rounded-2xl bg-white/[.025] p-5"><p className="section-kicker">What actually drives the scenario?</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{result.interpretation}</p></div><p className="mt-5 text-xs leading-5 text-[var(--muted-2)]">{result.disclaimer}</p></>}</Card></Reveal></div></div>
}
