"use client";
import Link from "next/link";
import { motion } from "motion/react";
import { ArrowRight, BrainCircuit, ChartNoAxesCombined, ChevronDown, CircleCheck, FlaskConical, Play, Sparkles, Target, ShieldCheck } from "lucide-react";
import { TiltCard, Reveal } from "@/components/ui/primitives";
import { Button } from "@/components/ui/button";
const demo=[['RELIANCE','Reliance Industries','₹1,482','84','29'],['TCS','Tata Consultancy Services','₹3,912','88','21'],['NVDA','NVIDIA Corporation','$177','68','87']];
export default function Home(){return <div className="space-y-20 sm:space-y-28">
<section className="relative min-h-[calc(100vh-140px)] overflow-hidden rounded-[2.5rem] border border-[var(--line)] grid-bg px-6 py-12 sm:px-12 lg:px-20 lg:py-20"><div className="absolute -right-20 top-20 h-80 w-80 rounded-full border border-[var(--accent)]/10 bg-[var(--accent)]/[.025] blur-sm pulse-glow"/><div className="absolute right-[12%] top-[24%] hidden h-44 w-44 rounded-full border border-white/10 lg:block"/><div className="relative z-10 flex min-h-[68vh] items-center"><div className="max-w-5xl"><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="pill inline-flex items-center gap-2 px-3 py-1.5 text-xs text-[var(--muted)]"><Sparkles size={13} className="text-[var(--accent)]"/>AI-powered investment decision coach <span className="h-1 w-1 rounded-full bg-[var(--accent)]"/></motion.div><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.08}} className="mt-7 max-w-5xl text-[clamp(3.7rem,9vw,8.7rem)] font-black leading-[.82] tracking-[-.075em]">Don&apos;t invest because <span className="text-gradient">everyone else is.</span></motion.h1><motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.16}} className="mt-8 max-w-2xl text-base leading-7 text-[var(--muted)] sm:text-xl sm:leading-8">Understand the story behind an investment. Challenge your assumptions. See whether it actually fits <em className="text-white not-italic">you</em> before you commit real money.</motion.p><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.24}} className="mt-9 flex flex-wrap gap-3"><Link href="/onboarding"><Button className="h-12 rounded-full px-6">Build My Investor DNA <ArrowRight size={17}/></Button></Link><Link href="/explore"><Button variant="secondary" className="h-12 rounded-full px-6"><Play size={15}/>Explore an investment</Button></Link></motion.div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-2 text-xs text-[var(--muted)]"><span className="flex items-center gap-2"><CircleCheck size={14} className="text-[var(--success)]"/>No buy/sell signals</span><span className="flex items-center gap-2"><CircleCheck size={14} className="text-[var(--success)]"/>Transparent scenarios</span><span className="flex items-center gap-2"><CircleCheck size={14} className="text-[var(--success)]"/>Bias-aware</span></div></div></div></section>
<section><div className="mb-7 max-w-xl"><p className="section-kicker">The decision loop</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Slow down the moment that matters.</h2></div><div className="grid gap-4 md:grid-cols-3">{[[BrainCircuit,'01','Understand','Translate the numbers into a story you can actually reason about.'],[ShieldCheck,'02','Challenge','Expose the assumptions, contradictions and behavioral traps inside your thesis.'],[FlaskConical,'03','Simulate','Stress-test the decision with transparent bull, base and bear scenarios.']].map(([I,n,t,d],i)=>{const Icon=I as any;return <Reveal key={t as string} delay={i*.07}><TiltCard className="shine h-full p-6 sm:p-8"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon size={20}/></div><span className="text-xs text-[var(--muted-2)]">{n as string}</span></div><h3 className="mt-12 text-2xl font-bold">{t as string}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{d as string}</p></TiltCard></Reveal>})}</div></section>
<section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">Live market discovery</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">What&apos;s worth questioning?</h2></div><Link href="/explore" className="text-sm text-[var(--accent)]">Search the market <ArrowRight className="ml-1 inline" size={15}/></Link></div><div className="mt-7 grid gap-4 md:grid-cols-3">{demo.map((a,i)=><Reveal key={a[0]} delay={i*.06}><Link href={`/asset/${a[0]}`}><TiltCard className="p-6"><div className="flex items-start justify-between"><div><p className="text-xs text-[var(--muted)]">{a[0]} · Market asset</p><h3 className="mt-1 text-lg font-bold">{a[1]}</h3></div><ChartNoAxesCombined className="text-[var(--muted)]" size={20}/></div><p className="mt-12 text-3xl font-black">{a[2]}</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><span className="text-[var(--muted)]">Your fit <b className="ml-1 text-white">{a[3]}</b></span><span className="text-[var(--muted)]">Hype <b className="ml-1 text-white">{a[4]}</b></span></div></TiltCard></Link></Reveal>)}</div></section>
<section className="relative overflow-hidden rounded-[2.5rem] border border-[var(--line)] bg-white/[.02] p-7 sm:p-12"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_center,rgba(217,255,98,.09),transparent_65%)]"/><div className="relative max-w-3xl"><p className="section-kicker">The THESIS difference</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">An AI that challenges <span className="text-[var(--accent)]">why</span> you&apos;re investing.</h2><p className="mt-5 max-w-2xl text-[var(--muted)]">Not another terminal. Not a black-box “buy” score. THESIS turns financial data, your profile and your reasoning into one deliberate decision experience.</p><Link href="/onboarding" className="mt-8 inline-flex"><Button className="rounded-full px-6">Start the experience <ArrowRight size={17}/></Button></Link></div></section>
</div>}
