import Link from "next/link";
import { ArrowRight, BrainCircuit, FlaskConical, ShieldCheck, Sparkles, LineChart } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const assets=[{s:"RELIANCE",n:"Reliance Industries",p:"₹1,482",fit:84,hype:29},{s:"TCS",n:"Tata Consultancy Services",p:"₹3,912",fit:88,hype:21},{s:"NVIDIA",n:"NVIDIA Corporation",p:"$177",fit:68,hype:87}];
export default function Home(){return <div className="space-y-8">
  <section className="grid-bg glow overflow-hidden rounded-[2rem] border border-[var(--line)] p-7 sm:p-12 lg:p-16"><div className="max-w-4xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-white/[.04] px-3 py-1.5 text-xs text-[var(--muted)]"><Sparkles size={14} className="text-[var(--accent)]"/>AI-powered investment decision coach</div><h1 className="text-5xl font-black leading-[.95] tracking-[-.06em] sm:text-7xl">Don&apos;t invest because <span className="text-[var(--accent)]">everyone else is.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--muted)]">Understand the story behind an investment, challenge your assumptions, and see whether it actually fits you before you commit real money.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/onboarding"><Button>Start My Investment Profile <ArrowRight size={17}/></Button></Link><Link href="/explore"><Button variant="secondary">Explore an Investment</Button></Link></div></div></section>
  <div className="grid gap-4 md:grid-cols-3">{[[BrainCircuit,"Understand","Turn financial jargon into plain English."],[ShieldCheck,"Challenge","Let AI attack the weakest part of your thesis."],[FlaskConical,"Simulate","See transparent bull/base/bear scenarios."]].map(([Icon,t,d])=>{const I=Icon as any;return <Card key={t as string} className="p-6"><I className="text-[var(--accent)]" size={24}/><h3 className="mt-5 text-lg font-bold">{t as string}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{d as string}</p></Card>})}</div>
  <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[var(--muted)]">Demo market</p><h2 className="mt-1 text-2xl font-bold">What&apos;s worth questioning?</h2></div><Link href="/explore" className="text-sm text-[var(--accent)]">View all →</Link></div><div className="grid gap-4 md:grid-cols-3">{assets.map(a=><Link key={a.s} href={`/asset/${a.s}`}><Card className="p-5 transition hover:-translate-y-0.5 hover:border-white/20"><div className="flex justify-between"><div><p className="text-xs text-[var(--muted)]">{a.s}</p><h3 className="mt-1 font-bold">{a.n}</h3></div><LineChart className="text-[var(--muted)]"/></div><div className="mt-8 text-2xl font-bold">{a.p}</div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div><span className="text-[var(--muted)]">Your fit</span><b className="ml-2">{a.fit}</b></div><div><span className="text-[var(--muted)]">Hype</span><b className="ml-2">{a.hype}</b></div></div></Card></Link>)}</div></section>
</div>}
