"use client";
import { useState } from "react";
import { ArrowRight, Check, ChevronLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/api";
import { useRouter } from "next/navigation";
const steps=[{key:"goal",title:"What are you investing for?",items:["Build long-term wealth","Save for a major goal","Generate additional income","Grow aggressively","Learn investing"]},{key:"horizon",title:"How long can you leave your money invested?",items:["< 1 year","1–3 years","3–5 years","5–10 years","10+ years"]},{key:"risk",title:"Your ₹10,000 investment becomes ₹7,000 temporarily. What do you do?",items:["Sell immediately","Probably sell","Wait","Buy more","Buy aggressively"]},{key:"knowledge",title:"How familiar are you with investing?",items:["I’m completely new","I understand the basics","I’m comfortable with financial metrics","I actively research investments"]}];
export default function Onboarding(){const [step,setStep]=useState(0);const [answers,setAnswers]=useState<Record<string,string>>({});const router=useRouter();const s=steps[step];const done=step===steps.length-1;async function next(){if(!answers[s.key])return;if(done){await api('/investor-profile',{method:'POST',body:JSON.stringify({email:'demo@thesis.local',goal:answers.goal,riskTolerance:answers.risk,timeHorizon:answers.horizon,knowledgeLevel:answers.knowledge,growthPreference:'balanced',incomePreference:'growth'})}).catch(()=>{});router.push('/investor-dna')}else setStep(step+1)}return <div className="mx-auto max-w-3xl py-8"><div className="mb-8 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[var(--muted)]">Investor profile</p><h1 className="mt-2 text-3xl font-black">Build your Investor DNA</h1></div><span className="text-sm text-[var(--muted)]">{step+1}/{steps.length}</span></div><div className="h-1 rounded bg-white/10"><div className="h-1 rounded bg-[var(--accent)] transition-all" style={{width:`${((step+1)/steps.length)*100}%`}}/></div><Card className="mt-8 p-7"><h2 className="text-2xl font-bold">{s.title}</h2><div className="mt-7 grid gap-3">{s.items.map(item=><button key={item} onClick={()=>setAnswers({...answers,[s.key]:item})} className={`flex items-center justify-between rounded-2xl border p-4 text-left transition ${answers[s.key]===item?'border-[var(--accent)] bg-[var(--accent)]/10':'border-[var(--line)] bg-white/[.02] hover:bg-white/[.05]'}`}><span>{item}</span>{answers[s.key]===item&&<Check className="text-[var(--accent)]" size={18}/>}</button>)}</div><div className="mt-8 flex justify-between"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}><ChevronLeft/>Back</Button><Button disabled={!answers[s.key]} onClick={next}>{done?'Create My DNA':'Continue'} <ArrowRight size={17}/></Button></div></Card></div>}
