"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { AnimatePresence, motion } from "motion/react";
import { BookOpen, BrainCircuit, ChevronLeft, ChevronRight, Compass, FlaskConical, Home, Menu, PanelLeftClose, PanelLeftOpen, Search, Sparkles, WalletCards, X, ArrowUpRight } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { api } from "@/lib/api";

const nav = [["Home", "/dashboard", Home], ["Explore", "/explore", Compass], ["My Thesis", "/my-thesis", BrainCircuit], ["Simulator", "/simulate", FlaskConical], ["Watchlist", "/watchlist", WalletCards], ["Learn", "/learn", BookOpen]] as const;

export function Shell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const router = useRouter(); const [mobileOpen, setMobileOpen] = useState(false); const [collapsed, setCollapsed] = useState(false); const [q, setQ] = useState(""); const [results, setResults] = useState<any[]>([]); const requestId = useRef(0);
  useEffect(() => { setCollapsed(localStorage.getItem("thesis-sidebar-collapsed") === "1"); }, []);
  useEffect(() => { document.body.style.overflow = mobileOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [mobileOpen]);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") setMobileOpen(false); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  useEffect(() => { const id = ++requestId.current; const timer = window.setTimeout(() => { if (q.trim().length < 3) { setResults([]); return; } api<any[]>(`/assets/search?q=${encodeURIComponent(q)}`).then(r => { if (id === requestId.current) setResults(r); }).catch(() => { if (id === requestId.current) setResults([]); }); }, 550); return () => clearTimeout(timer); }, [q]);
  const toggleCollapse = () => { const next = !collapsed; setCollapsed(next); localStorage.setItem("thesis-sidebar-collapsed", next ? "1" : "0"); };
  const closeMobile = () => setMobileOpen(false);
  const width = collapsed ? "lg:w-[84px]" : "lg:w-[270px]";
  return <div className="min-h-screen noise">
    <AnimatePresence>{mobileOpen && <motion.button aria-label="Close navigation" className="fixed inset-0 z-[55] bg-black/65 backdrop-blur-sm lg:hidden" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={closeMobile} />}</AnimatePresence>
    <aside className={cn("fixed inset-y-0 left-0 z-[60] w-[290px] border-r border-[var(--line)] bg-[#07090d]/96 p-3 backdrop-blur-2xl transition-[width,transform] duration-300", width, mobileOpen ? "translate-x-0" : "-translate-x-full lg:translate-x-0")}>
      <div className={cn("flex h-14 items-center", collapsed ? "justify-center" : "justify-between px-2")}>
        <Link href="/" onClick={closeMobile} className="text-[22px] font-black tracking-[-.06em]">{collapsed ? "T" : <>THESIS<span className="text-[var(--accent)]">.</span></>}</Link>
        <button onClick={closeMobile} className="rounded-xl p-2 text-[var(--muted)] hover:bg-white/[.05] lg:hidden"><X size={18}/></button>
      </div>
      <button onClick={toggleCollapse} className="absolute -right-3 top-[68px] hidden h-7 w-7 place-items-center rounded-full border border-[var(--line-strong)] bg-[#0d1015] text-[var(--muted)] shadow-xl hover:text-white lg:grid" aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"}>{collapsed ? <PanelLeftOpen size={14}/> : <PanelLeftClose size={14}/>}</button>
      <div className="mt-7 space-y-1">{nav.map(([label, href, Icon]) => { const active = path === href || path.startsWith(href + "/"); return <Link key={href} href={href} onClick={closeMobile} title={collapsed ? label : undefined} className={cn("group relative flex items-center rounded-2xl py-3 text-sm transition", collapsed ? "justify-center" : "gap-3 px-3", active ? "bg-white/[.07] text-white" : "text-[var(--muted)] hover:bg-white/[.04] hover:text-white")}><Icon size={17}/><span className={cn("transition-opacity", collapsed && "hidden")}>{label}</span>{active && <motion.span layoutId="nav" className="absolute right-2 h-1.5 w-1.5 rounded-full bg-[var(--accent)]"/>}</Link>; })}</div>
      <div className="mt-7 border-t border-[var(--line)] pt-5"><Link href="/investor-dna" onClick={closeMobile} title={collapsed ? "Investor DNA" : undefined} className={cn("group block rounded-2xl border border-[var(--accent)]/15 bg-[var(--accent)]/[.06] p-3 transition hover:bg-[var(--accent)]/[.1]", collapsed && "px-2")}><div className={cn("flex items-center", collapsed ? "justify-center" : "gap-3")}><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[var(--accent)]/10 text-[var(--accent)]"><Sparkles size={16}/></div>{!collapsed && <div><b className="text-sm">Investor DNA</b><p className="mt-0.5 text-[11px] text-[var(--muted)]">Your decision profile</p></div>}</div></Link></div>
      {!collapsed && <div className="absolute bottom-5 left-4 right-4 rounded-2xl border border-[var(--line)] bg-white/[.025] p-3 text-[11px] leading-5 text-[var(--muted)]"><span className="text-white">THESIS</span> is educational. Not financial advice.</div>}
    </aside>
    <header className={cn("sticky top-0 z-40 border-b border-[var(--line)] bg-[#050608]/78 backdrop-blur-2xl transition-[padding] duration-300", collapsed ? "lg:pl-[84px]" : "lg:pl-[270px]")}><div className="flex h-[72px] items-center gap-3 px-4 sm:px-6 lg:px-9">
      <button onClick={() => setMobileOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl border border-[var(--line)] bg-white/[.03] text-[var(--muted)] hover:text-white lg:hidden"><Menu size={18}/></button>
      <div className="relative hidden w-full max-w-xl sm:block"><div className="flex h-11 items-center gap-2 rounded-2xl border border-[var(--line)] bg-white/[.025] px-3 focus-within:border-white/20"><Search size={16} className="text-[var(--muted)]"/><input value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && q.trim()) { router.push(`/explore?q=${encodeURIComponent(q)}`); setResults([]); } }} placeholder="Search stocks, ETFs, companies…" className="w-full bg-transparent text-sm outline-none placeholder:text-[var(--muted-2)]"/><kbd className="hidden rounded-md border border-[var(--line)] px-1.5 py-0.5 text-[10px] text-[var(--muted)] md:block">⌘ K</kbd></div><AnimatePresence>{results.length > 0 && <motion.div initial={{ opacity: 0, y: -5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="absolute left-0 right-0 top-13 z-50 overflow-hidden rounded-2xl border border-[var(--line-strong)] bg-[#0d0f14]/98 p-2 shadow-2xl backdrop-blur-2xl">{results.slice(0, 6).map(a => <button key={a.symbol} onClick={() => { setQ(""); router.push(`/asset/${encodeURIComponent(a.symbol)}`); }} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left hover:bg-white/[.05]"><div className="grid h-8 w-8 place-items-center rounded-lg bg-white/[.06] text-xs font-bold">{a.symbol.slice(0, 2)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{a.name}</p><p className="text-[11px] text-[var(--muted)]">{a.symbol} · {a.exchange}</p></div><ArrowUpRight size={14} className="text-[var(--muted)]"/></button>)}</motion.div>}</AnimatePresence></div>
      <div className="ml-auto flex items-center gap-2"><Link href="/explore" className="grid h-10 w-10 place-items-center rounded-xl border border-[var(--line)] bg-white/[.03] text-[var(--muted)] hover:text-white sm:hidden"><Search size={18}/></Link><Link href="/investor-dna" className="flex items-center gap-2 rounded-full border border-[var(--line)] bg-white/[.03] px-3 py-1.5 text-xs hover:bg-white/[.06]"><span className="grid h-5 w-5 place-items-center rounded-full bg-[var(--accent)] text-black"><Sparkles size={11}/></span><span className="hidden sm:inline">Investor DNA</span></Link></div>
    </div></header>
    <main className={cn("transition-[padding] duration-300", collapsed ? "lg:pl-[84px]" : "lg:pl-[270px]")}><div className="mx-auto max-w-[1450px] px-4 py-7 sm:px-6 lg:px-9 lg:py-10">{children}</div></main>
  </div>;
}
