"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { AnimatePresence, motion } from "motion/react";
import { BookOpen, BrainCircuit, Compass, FlaskConical, Home, Menu, Search, Sparkles, WalletCards, X, ArrowUpRight } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { api } from "@/lib/api";

const nav=[['Home','/dashboard',Home],['Explore','/explore',Compass],['My Thesis','/my-thesis',BrainCircuit],['Simulator','/simulate',FlaskConical],['Watchlist','/watchlist',WalletCards],['Learn','/learn',BookOpen]] as const;
export function Shell({children}:{children:React.ReactNode}){const path=usePathname(); const router=useRouter(); const [open,setOpen]=useState(false); const [q,setQ]=useState(''); const [results,setResults]=useState<any[]>([]); const requestId=useRef(0);
useEffect(()=>{const id=++requestId.current; const t=setTimeout(()=>{if(q.trim().length<2){setResults([]);return} api<any[]>(`/assets/search?q=${encodeURIComponent(q)}`).then(r=>{if(id===requestId.current)setResults(r)}).catch(()=>{if(id===requestId.current)setResults([])})},320); return()=>clearTimeout(t)},[q]);
return <div className="min-h-screen noise"><aside className={cn("fixed inset-y-0 left-0 z-50 w-[270px] border-r border-[var(--line)] bg-[#07090d]/92 p-4 backdrop-blur-2xl transition-transform lg:translate-x-0",open?'translate-x-0':'-translate-x-full')}>
<div className="flex items-center justify-between px-2 py-3"><Link href="/" className="text-[22px] font-black tracking-[-.06em]">THESIS<span className="text-[var(--accent)]">.</span></Link><button className="lg:hidden text-[var(--muted)]" onClick={()=>setOpen(false)}><X size={18}/></button></div>
<div className="mt-8 space-y-1">{nav.map(([label,href,Icon])=>{const active=path===href||path.startsWith(href+'/'); return <Link key={href} href={href} onClick={()=>setOpen(false)} className={cn('group relative flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition',active?'bg-white/[.07] text-white':'text-[var(--muted)] hover:bg-white/[.04] hover:text-white')}><Icon size={17}/><span>{label}</span>{active&&<motion.span layoutId="nav" className="absolute right-2 h-1.5 w-1.5 rounded-full bg-[var(--accent)]"/>}</Link>})}</div>
<div className="mt-8 border-t border-[var(--line)] pt-5"><Link href="/investor-dna" className="group block rounded-2xl border border-[var(--accent)]/15 bg-[var(--accent)]/[.06] p-3 transition hover:bg-[var(--accent)]/[.1]"><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[var(--accent)]/10 text-[var(--accent)]"><Sparkles size={16}/></div><div><b className="text-sm">Investor DNA</b><p className="mt-0.5 text-[11px] text-[var(--muted)]">Your decision profile</p></div></div></Link></div>
<div className="absolute bottom-5 left-5 right-5"><div className="rounded-2xl border border-[var(--line)] bg-white/[.025] p-3 text-xs text-[var(--muted)]"><span className="text-white">THESIS</span> is educational. Not financial advice.</div></div></aside>
<header className="sticky top-0 z-40 border-b border-[var(--line)] bg-[#050608]/75 backdrop-blur-2xl lg:pl-[270px]"><div className="flex h-[72px] items-center gap-3 px-4 sm:px-6 lg:px-9"><button onClick={()=>setOpen(true)} className="rounded-xl p-2 text-[var(--muted)] lg:hidden"><Menu/></button><div className="relative hidden w-full max-w-xl sm:block"><div className="flex h-10 items-center gap-2 rounded-xl border border-[var(--line)] bg-white/[.025] px-3 focus-within:border-white/20"><Search size={16} className="text-[var(--muted)]"/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&q.trim()){router.push(`/explore?q=${encodeURIComponent(q)}`);setResults([])}}} placeholder="Search stocks, ETFs, companies..." className="w-full bg-transparent text-sm outline-none placeholder:text-[var(--muted-2)]"/><kbd className="rounded-md border border-[var(--line)] px-1.5 py-0.5 text-[10px] text-[var(--muted)]">⌘ K</kbd></div><AnimatePresence>{results.length>0&&<motion.div initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="absolute left-0 right-0 top-12 z-50 overflow-hidden rounded-2xl border border-[var(--line-strong)] bg-[#0d0f14]/98 p-2 shadow-2xl backdrop-blur-2xl">{results.slice(0,6).map(a=><button key={a.symbol} onClick={()=>{setQ('');router.push(`/asset/${encodeURIComponent(a.symbol)}`)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left hover:bg-white/[.05]"><div className="grid h-8 w-8 place-items-center rounded-lg bg-white/[.06] text-xs font-bold">{a.symbol.slice(0,2)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{a.name}</p><p className="text-[11px] text-[var(--muted)]">{a.symbol} · {a.exchange}</p></div><ArrowUpRight size={14} className="text-[var(--muted)]"/></button>)}</motion.div>}</AnimatePresence></div><div className="ml-auto flex items-center gap-2"><Link href="/explore" className="rounded-xl p-2 text-[var(--muted)] hover:bg-white/[.05] sm:hidden"><Search size={18}/></Link><Link href="/investor-dna" className="flex items-center gap-2 rounded-full border border-[var(--line)] bg-white/[.03] px-3 py-1.5 text-xs hover:bg-white/[.06]"><span className="grid h-5 w-5 place-items-center rounded-full bg-[var(--accent)] text-black">R</span><span className="hidden sm:inline">Investor DNA</span></Link></div></div></header>
<main className="lg:pl-[270px]"><div className="mx-auto max-w-[1450px] px-4 py-7 sm:px-6 lg:px-9 lg:py-10">{children}</div></main></div>}
