"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BrainCircuit, Clock3, LoaderCircle } from "lucide-react";
import { motion } from "motion/react";
import { api } from "@/lib/api";
import { getUserId } from "@/lib/user";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ScoreRing } from "@/components/ui/primitives";
export default function MyThesis() {
  const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { api<any[]>(`/thesis?userId=${encodeURIComponent(getUserId())}`).then(setData).catch(e => setError(e?.message || "Could not load your thesis journal.")).finally(() => setLoading(false)); }, []);
  return <div className="space-y-8"><div><p className="section-kicker">Your investment journal</p><h1 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-6xl">My <span className="text-[var(--accent)]">thesis.</span></h1><p className="mt-4 max-w-2xl text-[var(--muted)]">Make your reasoning visible enough to revisit. A saved thesis is a record of what you believed, not a guarantee that you were right.</p></div>{loading ? <Card className="grid min-h-[300px] place-items-center"><LoaderCircle className="animate-spin text-[var(--accent)]"/></Card> : error ? <Card className="p-7"><p className="font-semibold">Journal unavailable</p><p className="mt-2 text-sm text-[var(--muted)]">{error}</p></Card> : data.length ? <div className="grid gap-4 md:grid-cols-2">{data.map((x, i) => { let analysis: any = {}; try { analysis = typeof x.analysis_json === "string" ? JSON.parse(x.analysis_json) : (x.analysis_json || {}); } catch {} return <motion.div key={x.id} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * .05 }}><Card className="glass-hover p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-[var(--muted)]">{x.symbol} · {x.name}</p><p className="mt-3 line-clamp-3 text-lg font-semibold leading-7">“{x.thesis_text}”</p></div><ScoreRing value={Number(x.thesis_score || 0)} size={70}/></div><div className="mt-5 flex flex-wrap gap-2 text-xs"><span className="pill px-2.5 py-1">{x.decision}</span>{analysis.finalScore != null && <span className="pill px-2.5 py-1">Final {analysis.finalScore}</span>}{analysis.biases?.[0]?.name && <span className="pill px-2.5 py-1">{analysis.biases[0].name}</span>}</div><div className="mt-6 flex items-center justify-between border-t border-[var(--line)] pt-4"><div className="flex items-center gap-2 text-xs text-[var(--muted)]"><Clock3 size={14}/>{new Date(x.created_at).toLocaleDateString()}</div><Link href={`/thesis/${x.symbol}`} className="text-xs font-semibold text-[var(--accent)]">Re-evaluate <ArrowRight className="ml-1 inline" size={13}/></Link></div></Card></motion.div>; })}</div> : <Card className="grid min-h-[420px] place-items-center p-8 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><BrainCircuit/></div><h2 className="mt-5 text-2xl font-bold">No thesis saved yet.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--muted)]">Search a live asset, write why you believe in it, challenge the reasoning and save the result.</p><Link href="/explore" className="mt-6 inline-flex"><Button>Find an investment <ArrowRight size={16}/></Button></Link></div></Card>}</div>;
}
