"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Bookmark, LoaderCircle, Trash2 } from "lucide-react";
import { api } from "@/lib/api";
import { getUserId } from "@/lib/user";
import { moneyForCurrency } from "@/lib/utils";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ScoreRing, Progress } from "@/components/ui/primitives";
export default function Watchlist() {
  const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = () => api<any[]>(`/watchlist?userId=${encodeURIComponent(getUserId())}`).then(setData).catch(e => setError(e?.message || "Could not load your watchlist.")).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const remove = async (symbol: string) => { try { await api(`/watchlist/${encodeURIComponent(symbol)}?userId=${encodeURIComponent(getUserId())}`, { method: "POST" }); setData(items => items.filter(d => d.asset.symbol !== symbol)); } catch (e: any) { setError(e?.message || "Could not remove this asset."); } };
  return <div className="space-y-8"><div><p className="section-kicker">Your radar</p><h1 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-6xl">Watch <span className="text-[var(--accent)]">closely.</span></h1><p className="mt-4 text-[var(--muted)]">Only assets you explicitly saved appear here. Market values are refreshed from the live provider when the page loads.</p></div>{loading ? <Card className="grid min-h-[300px] place-items-center"><LoaderCircle className="animate-spin text-[var(--accent)]"/></Card> : error ? <Card className="p-7"><p className="font-semibold">Watchlist unavailable</p><p className="mt-2 text-sm text-[var(--muted)]">{error}</p></Card> : <div className="grid gap-4">{data.map((d: any) => <Card key={d.asset.symbol} className="p-5 sm:p-6"><div className="grid gap-5 md:grid-cols-[1.3fr_.7fr_1fr_auto] md:items-center"><div><p className="text-xs text-[var(--muted)]">{d.asset.symbol} · {d.asset.exchange}</p><h2 className="mt-1 text-xl font-bold">{d.asset.name}</h2><p className="mt-1 text-xs text-[var(--muted)]">{d.asset.sector}</p></div><div className="flex items-center gap-3"><ScoreRing value={d.personalFit.score} size={62} label="fit"/><div><p className="text-xs text-[var(--muted)]">Price</p><p className="font-bold">{moneyForCurrency(Number(d.asset.price), d.asset.currency, 2)}</p></div></div><div className="grid grid-cols-2 gap-5"><div><p className="mb-2 text-xs text-[var(--muted)]">Risk {d.risk.score ?? "—"}</p><Progress value={Number(d.risk.score || 0)} tone={Number(d.risk.score) > 60 ? "danger" : "accent"}/></div><div><p className="mb-2 text-xs text-[var(--muted)]">Hype {d.hype.score ?? "—"}</p><Progress value={Number(d.hype.score || 0)} tone={Number(d.hype.score) > 60 ? "danger" : "blue"}/></div></div><div className="flex gap-2"><Link href={`/asset/${d.asset.symbol}`} className="inline-flex items-center justify-center rounded-xl border border-[var(--line)] p-3 hover:bg-white/[.05]"><ArrowRight size={17}/></Link><button onClick={() => remove(d.asset.symbol)} className="inline-flex items-center justify-center rounded-xl border border-[var(--line)] p-3 text-[var(--muted)] hover:border-[var(--danger)]/30 hover:text-[var(--danger)]" aria-label={`Remove ${d.asset.name}`}><Trash2 size={17}/></button></div></div></Card>)}{!data.length && <Card className="p-12 text-center text-sm text-[var(--muted)]"><Bookmark className="mx-auto mb-3"/>Your watchlist is empty. Nothing is preloaded.<div className="mt-5"><Link href="/explore"><Button>Explore live market <ArrowRight size={15}/></Button></Link></div></Card>}</div>}</div>;
}
